
MODE: 'semantic'

PATHS:
  DATASET_ROOT: '/storage/datasets/marine/LaRS/v0.9/test'
  PREDICTIONS: '/path/to/predictions/segmentation_v0.9'
  RESULTS: './results/v0.9/semantic'

DATASET:
  IMAGE_SUBDIR: 'images'
  SEMANTIC_MASK_SUBDIR: 'semantic_masks'
  PANOPTIC_MASK_SUBDIR: 'panoptic_masks'
  PANOPTIC_ANN_FILE: 'panoptic_annotations.json'
  SUBSET_LIST: 'image_list.txt'

SEGMENTATION:
  # Colors used in the predictions masks
  COLORS: 
    - [247, 195,  37] # Obstacles RGB color
    - [ 41, 167, 224] # Water RGB color
    - [ 90,  75, 164] # Sky RGB color

PROGRESS:
  METRICS: ['mIoU', 'WE_acc', 'F1']
  