
PATHS:
  DATASET_ROOT: '/home/lojze/data/datasets/LaRS'
  PREDICTIONS: '/home/lojze/data/predictions/lars'
  RESULTS: './results'

DATASET:
  IMAGE_SUBDIR: 'images'
  GT_MASK_SUBDIR: 'masks'
  INST_MASK_SUBDIR: 'instances'
  SUBSET_LIST: 'list_test.txt'

CLASSES:
  # Colors used in the predictions masks
  COLORS: 
    - [247, 195,  37] # Obstacles RGB color
    - [ 41, 167, 224] # Water RGB color
    - [ 90,  75, 164] # Sky RGB color
