
MODE: 'semantic'

PATHS:
  DATASET_ROOT: '/home/lojze/data/datasets/LaRS/split/test'
  PREDICTIONS: '/home/lojze/data/predictions/lars/segmentation'
  RESULTS: './results'

DATASET:
  IMAGE_SUBDIR: 'images'
  SEMANTIC_MASK_SUBDIR: 'semantic_masks'
  PANOPTIC_MASK_SUBDIR: 'panoptic_masks'
  PANOPTIC_ANN_FILE: 'panoptic_annotations.json'
  SUBSET_LIST: 'image_list.txt'

SEGMENTATION:
  # Colors used in the predictions masks
  COLORS: 
    - [247, 195,  37] # Obstacles RGB color
    - [ 41, 167, 224] # Water RGB color
    - [ 90,  75, 164] # Sky RGB color

PROGRESS:
  METRICS: ['mIoU', 'WE_acc', 'F1']
  